###
Get http://localhost:3000/api/v1/

###
Get http://localhost:3000/api/v1/62a031721a598c9a8ce0597f

###
Post http://localhost:3000/api/v1/
Content-Type: application/json

{
  "name": "test",
  "email": "fernando5",
  "password": "123456"
}

###
Put http://localhost:3000/api/v1/62a0327ba5152c0766ee96c8
Content-Type: application/json

{
    "name": "fernando"
}

###
Delete http://localhost:3000/api/v1/62a0328a47cb1671db870b6f